/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSupplierIndexRouteImport } from './routes/_app.supplier.index'
import { Route as AppParkIndexRouteImport } from './routes/_app.park.index'
import { Route as AppFreelancerIndexRouteImport } from './routes/_app.freelancer.index'
import { Route as AppSupplierJobsRouteImport } from './routes/_app.supplier.jobs'
import { Route as AppParkAssetsRouteImport } from './routes/_app.park.assets'
import { Route as AppParkAnalyticsRouteImport } from './routes/_app.park.analytics'
import { Route as AppFreelancerOpportunitiesRouteImport } from './routes/_app.freelancer.opportunities'
import { Route as AppParkTicketsIndexRouteImport } from './routes/_app.park.tickets.index'
import { Route as AppParkTicketsNewRouteImport } from './routes/_app.park.tickets.new'
import { Route as AppParkTicketsIdRouteImport } from './routes/_app.park.tickets.$id'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSupplierIndexRoute = AppSupplierIndexRouteImport.update({
  id: '/supplier/',
  path: '/supplier/',
  getParentRoute: () => AppRoute,
} as any)
const AppParkIndexRoute = AppParkIndexRouteImport.update({
  id: '/park/',
  path: '/park/',
  getParentRoute: () => AppRoute,
} as any)
const AppFreelancerIndexRoute = AppFreelancerIndexRouteImport.update({
  id: '/freelancer/',
  path: '/freelancer/',
  getParentRoute: () => AppRoute,
} as any)
const AppSupplierJobsRoute = AppSupplierJobsRouteImport.update({
  id: '/supplier/jobs',
  path: '/supplier/jobs',
  getParentRoute: () => AppRoute,
} as any)
const AppParkAssetsRoute = AppParkAssetsRouteImport.update({
  id: '/park/assets',
  path: '/park/assets',
  getParentRoute: () => AppRoute,
} as any)
const AppParkAnalyticsRoute = AppParkAnalyticsRouteImport.update({
  id: '/park/analytics',
  path: '/park/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppFreelancerOpportunitiesRoute =
  AppFreelancerOpportunitiesRouteImport.update({
    id: '/freelancer/opportunities',
    path: '/freelancer/opportunities',
    getParentRoute: () => AppRoute,
  } as any)
const AppParkTicketsIndexRoute = AppParkTicketsIndexRouteImport.update({
  id: '/park/tickets/',
  path: '/park/tickets/',
  getParentRoute: () => AppRoute,
} as any)
const AppParkTicketsNewRoute = AppParkTicketsNewRouteImport.update({
  id: '/park/tickets/new',
  path: '/park/tickets/new',
  getParentRoute: () => AppRoute,
} as any)
const AppParkTicketsIdRoute = AppParkTicketsIdRouteImport.update({
  id: '/park/tickets/$id',
  path: '/park/tickets/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/freelancer/opportunities': typeof AppFreelancerOpportunitiesRoute
  '/park/analytics': typeof AppParkAnalyticsRoute
  '/park/assets': typeof AppParkAssetsRoute
  '/supplier/jobs': typeof AppSupplierJobsRoute
  '/freelancer/': typeof AppFreelancerIndexRoute
  '/park/': typeof AppParkIndexRoute
  '/supplier/': typeof AppSupplierIndexRoute
  '/park/tickets/$id': typeof AppParkTicketsIdRoute
  '/park/tickets/new': typeof AppParkTicketsNewRoute
  '/park/tickets/': typeof AppParkTicketsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/freelancer/opportunities': typeof AppFreelancerOpportunitiesRoute
  '/park/analytics': typeof AppParkAnalyticsRoute
  '/park/assets': typeof AppParkAssetsRoute
  '/supplier/jobs': typeof AppSupplierJobsRoute
  '/freelancer': typeof AppFreelancerIndexRoute
  '/park': typeof AppParkIndexRoute
  '/supplier': typeof AppSupplierIndexRoute
  '/park/tickets/$id': typeof AppParkTicketsIdRoute
  '/park/tickets/new': typeof AppParkTicketsNewRoute
  '/park/tickets': typeof AppParkTicketsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/_app/freelancer/opportunities': typeof AppFreelancerOpportunitiesRoute
  '/_app/park/analytics': typeof AppParkAnalyticsRoute
  '/_app/park/assets': typeof AppParkAssetsRoute
  '/_app/supplier/jobs': typeof AppSupplierJobsRoute
  '/_app/freelancer/': typeof AppFreelancerIndexRoute
  '/_app/park/': typeof AppParkIndexRoute
  '/_app/supplier/': typeof AppSupplierIndexRoute
  '/_app/park/tickets/$id': typeof AppParkTicketsIdRoute
  '/_app/park/tickets/new': typeof AppParkTicketsNewRoute
  '/_app/park/tickets/': typeof AppParkTicketsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/freelancer/opportunities'
    | '/park/analytics'
    | '/park/assets'
    | '/supplier/jobs'
    | '/freelancer/'
    | '/park/'
    | '/supplier/'
    | '/park/tickets/$id'
    | '/park/tickets/new'
    | '/park/tickets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/freelancer/opportunities'
    | '/park/analytics'
    | '/park/assets'
    | '/supplier/jobs'
    | '/freelancer'
    | '/park'
    | '/supplier'
    | '/park/tickets/$id'
    | '/park/tickets/new'
    | '/park/tickets'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/onboarding'
    | '/_app/freelancer/opportunities'
    | '/_app/park/analytics'
    | '/_app/park/assets'
    | '/_app/supplier/jobs'
    | '/_app/freelancer/'
    | '/_app/park/'
    | '/_app/supplier/'
    | '/_app/park/tickets/$id'
    | '/_app/park/tickets/new'
    | '/_app/park/tickets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/supplier/': {
      id: '/_app/supplier/'
      path: '/supplier'
      fullPath: '/supplier/'
      preLoaderRoute: typeof AppSupplierIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/park/': {
      id: '/_app/park/'
      path: '/park'
      fullPath: '/park/'
      preLoaderRoute: typeof AppParkIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/freelancer/': {
      id: '/_app/freelancer/'
      path: '/freelancer'
      fullPath: '/freelancer/'
      preLoaderRoute: typeof AppFreelancerIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/supplier/jobs': {
      id: '/_app/supplier/jobs'
      path: '/supplier/jobs'
      fullPath: '/supplier/jobs'
      preLoaderRoute: typeof AppSupplierJobsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/park/assets': {
      id: '/_app/park/assets'
      path: '/park/assets'
      fullPath: '/park/assets'
      preLoaderRoute: typeof AppParkAssetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/park/analytics': {
      id: '/_app/park/analytics'
      path: '/park/analytics'
      fullPath: '/park/analytics'
      preLoaderRoute: typeof AppParkAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/freelancer/opportunities': {
      id: '/_app/freelancer/opportunities'
      path: '/freelancer/opportunities'
      fullPath: '/freelancer/opportunities'
      preLoaderRoute: typeof AppFreelancerOpportunitiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/park/tickets/': {
      id: '/_app/park/tickets/'
      path: '/park/tickets'
      fullPath: '/park/tickets/'
      preLoaderRoute: typeof AppParkTicketsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/park/tickets/new': {
      id: '/_app/park/tickets/new'
      path: '/park/tickets/new'
      fullPath: '/park/tickets/new'
      preLoaderRoute: typeof AppParkTicketsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/park/tickets/$id': {
      id: '/_app/park/tickets/$id'
      path: '/park/tickets/$id'
      fullPath: '/park/tickets/$id'
      preLoaderRoute: typeof AppParkTicketsIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppFreelancerOpportunitiesRoute: typeof AppFreelancerOpportunitiesRoute
  AppParkAnalyticsRoute: typeof AppParkAnalyticsRoute
  AppParkAssetsRoute: typeof AppParkAssetsRoute
  AppSupplierJobsRoute: typeof AppSupplierJobsRoute
  AppFreelancerIndexRoute: typeof AppFreelancerIndexRoute
  AppParkIndexRoute: typeof AppParkIndexRoute
  AppSupplierIndexRoute: typeof AppSupplierIndexRoute
  AppParkTicketsIdRoute: typeof AppParkTicketsIdRoute
  AppParkTicketsNewRoute: typeof AppParkTicketsNewRoute
  AppParkTicketsIndexRoute: typeof AppParkTicketsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppFreelancerOpportunitiesRoute: AppFreelancerOpportunitiesRoute,
  AppParkAnalyticsRoute: AppParkAnalyticsRoute,
  AppParkAssetsRoute: AppParkAssetsRoute,
  AppSupplierJobsRoute: AppSupplierJobsRoute,
  AppFreelancerIndexRoute: AppFreelancerIndexRoute,
  AppParkIndexRoute: AppParkIndexRoute,
  AppSupplierIndexRoute: AppSupplierIndexRoute,
  AppParkTicketsIdRoute: AppParkTicketsIdRoute,
  AppParkTicketsNewRoute: AppParkTicketsNewRoute,
  AppParkTicketsIndexRoute: AppParkTicketsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
